# Serena Project Configuration for Pulumi Cloud-Native Enterprise Platform
# =============================================================================

# Languages for which language servers are started
# TypeScript handles both .ts and .js files
# YAML is added for Pulumi configuration files (Pulumi.*.yaml)
languages:
- typescript
- yaml

# File encoding
encoding: "utf-8"

# Use .gitignore to filter files
ignore_all_files_in_gitignore: true

# Additional paths to ignore (beyond .gitignore)
# These help Serena focus on relevant source code
ignored_paths:
  # Compiled JavaScript outputs (source is in .ts files)
  - "packages/core/*.js"
  - "packages/core/*.d.ts"
  - "packages/core/config/*.js"
  - "packages/core/config/*.d.ts"
  # Node modules in all locations
  - "**/node_modules/**"
  # Build outputs
  - "**/dist/**"
  - "**/*.js.map"
  # Lock files
  - "pnpm-lock.yaml"
  - "package-lock.json"
  # IDE/Editor directories
  - ".vscode/**"
  - ".idea/**"
  # OS files
  - ".DS_Store"
  - "**/.DS_Store"

# Read-only mode (disabled - allow edits)
read_only: false

# No tools excluded - use all available tools
excluded_tools: []

# Project name
project_name: "pulumi-cloud-native-enterprise-platform"

# Optional tools (none needed currently)
included_optional_tools: []

# Initial prompt to provide context about the project
initial_prompt: |
  This is a Pulumi Infrastructure-as-Code (IaC) project for deploying a multi-tenant,
  multi-region cloud-native platform on Azure.

  ## Project Structure

  **Source Code:**
  - `packages/core/lib/` - Core TypeScript library (config loading, naming, tagging, interfaces)
  - `stacks/` - Pulumi stacks organized by deployment order:
    - `00-state-backend/` - Pulumi state storage setup
    - `01-bootstrap/` - Azure policies and management groups
    - `02-platform-services/` - Core platform infrastructure
    - `03-services-addons/` - Additional services
    - `04-application-services/` - Application-level services

  **Configuration:**
  - `config/examples/` - Example YAML configurations for different scenarios
  - `Pulumi.*.yaml` files in each stack - Stack-specific configurations

  **Documentation:**
  - `docs/` - Architecture, implementation guides, and user documentation

  ## Key Patterns
  - Uses pnpm workspaces for monorepo management
  - TypeScript with strict mode enabled
  - Path aliases: `@enterprise/core` -> `packages/core`
  - Pulumi for infrastructure deployment to Azure

  ## When Working on This Project
  - Core library source is in `packages/core/lib/` (not root .js/.d.ts files)
  - Each stack has its own `package.json` and `tsconfig.json`
  - Configuration schemas are in `packages/core/lib/config/schema.ts`
